package generator

import "google.golang.org/protobuf/compiler/protogen"

// A Plugin provides functionality to add to the output during Go code generation,
// such as to produce RPC stubs.
type Plugin interface {
	// Name identifies the plugin.
	Name() string

	// Version identifies the plugin version.
	Version() string

	// Init is called once before code generated.
	// The `file` will be ignore if return false.
	Init(file *protogen.File) bool

	// Generate produces the code generated by the plugin for this file,
	// except for the imports, by calling the generator's methods P, In, and Out.
	Generate(g *protogen.GeneratedFile)
}
