// Code generated by protoc-gen-godefaults. DO NOT EDIT.
// versions:
// 		protoc-gen-godefaults 0.0.2
// source: xgo/tests/godefaultsexternal/godefaults_external.proto

package godefaultsexternal

// Set default value for message godefaultsexternal.ExternalMessage1
func (this *ExternalMessage1) SetDefaults() {
	if this == nil {
		return
	}
	return
}
