// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: xgo/tests/gosqltest/gosql_test.proto

package gosqltest

import (
	_ "github.com/yu31/protoc-plugin/xgo/pb/pbgosql"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
type User1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta1 *User1_Meta1 `protobuf:"bytes,2,opt,name=meta1,proto3" json:"meta1,omitempty"`
}

func (x *User1) Reset() {
	*x = User1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User1) ProtoMessage() {}

func (x *User1) ProtoReflect() protoreflect.Message {
	mi := &file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User1.ProtoReflect.Descriptor instead.
func (*User1) Descriptor() ([]byte, []int) {
	return file_xgo_tests_gosqltest_gosql_test_proto_rawDescGZIP(), []int{0}
}

func (x *User1) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User1) GetMeta1() *User1_Meta1 {
	if x != nil {
		return x.Meta1
	}
	return nil
}

type User2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *User2) Reset() {
	*x = User2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User2) ProtoMessage() {}

func (x *User2) ProtoReflect() protoreflect.Message {
	mi := &file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User2.ProtoReflect.Descriptor instead.
func (*User2) Descriptor() ([]byte, []int) {
	return file_xgo_tests_gosqltest_gosql_test_proto_rawDescGZIP(), []int{1}
}

func (x *User2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type User3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *User3) Reset() {
	*x = User3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User3) ProtoMessage() {}

func (x *User3) ProtoReflect() protoreflect.Message {
	mi := &file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User3.ProtoReflect.Descriptor instead.
func (*User3) Descriptor() ([]byte, []int) {
	return file_xgo_tests_gosqltest_gosql_test_proto_rawDescGZIP(), []int{2}
}

func (x *User3) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type User4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *User4) Reset() {
	*x = User4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User4) ProtoMessage() {}

func (x *User4) ProtoReflect() protoreflect.Message {
	mi := &file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User4.ProtoReflect.Descriptor instead.
func (*User4) Descriptor() ([]byte, []int) {
	return file_xgo_tests_gosqltest_gosql_test_proto_rawDescGZIP(), []int{3}
}

func (x *User4) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type User5 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *User5) Reset() {
	*x = User5{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User5) ProtoMessage() {}

func (x *User5) ProtoReflect() protoreflect.Message {
	mi := &file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User5.ProtoReflect.Descriptor instead.
func (*User5) Descriptor() ([]byte, []int) {
	return file_xgo_tests_gosqltest_gosql_test_proto_rawDescGZIP(), []int{4}
}

func (x *User5) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type User6 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *User6) Reset() {
	*x = User6{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User6) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User6) ProtoMessage() {}

func (x *User6) ProtoReflect() protoreflect.Message {
	mi := &file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User6.ProtoReflect.Descriptor instead.
func (*User6) Descriptor() ([]byte, []int) {
	return file_xgo_tests_gosqltest_gosql_test_proto_rawDescGZIP(), []int{5}
}

func (x *User6) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type User7 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *User7) Reset() {
	*x = User7{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User7) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User7) ProtoMessage() {}

func (x *User7) ProtoReflect() protoreflect.Message {
	mi := &file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User7.ProtoReflect.Descriptor instead.
func (*User7) Descriptor() ([]byte, []int) {
	return file_xgo_tests_gosqltest_gosql_test_proto_rawDescGZIP(), []int{6}
}

func (x *User7) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type User1_Meta1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Age   int64              `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	Meta1 *User1_Meta1_Meta2 `protobuf:"bytes,2,opt,name=meta1,proto3" json:"meta1,omitempty"`
}

func (x *User1_Meta1) Reset() {
	*x = User1_Meta1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User1_Meta1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User1_Meta1) ProtoMessage() {}

func (x *User1_Meta1) ProtoReflect() protoreflect.Message {
	mi := &file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User1_Meta1.ProtoReflect.Descriptor instead.
func (*User1_Meta1) Descriptor() ([]byte, []int) {
	return file_xgo_tests_gosqltest_gosql_test_proto_rawDescGZIP(), []int{0, 0}
}

func (x *User1_Meta1) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *User1_Meta1) GetMeta1() *User1_Meta1_Meta2 {
	if x != nil {
		return x.Meta1
	}
	return nil
}

type User1_Meta1_Meta2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sex int64 `protobuf:"varint,1,opt,name=sex,proto3" json:"sex,omitempty"`
}

func (x *User1_Meta1_Meta2) Reset() {
	*x = User1_Meta1_Meta2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User1_Meta1_Meta2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User1_Meta1_Meta2) ProtoMessage() {}

func (x *User1_Meta1_Meta2) ProtoReflect() protoreflect.Message {
	mi := &file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User1_Meta1_Meta2.ProtoReflect.Descriptor instead.
func (*User1_Meta1_Meta2) Descriptor() ([]byte, []int) {
	return file_xgo_tests_gosqltest_gosql_test_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *User1_Meta1_Meta2) GetSex() int64 {
	if x != nil {
		return x.Sex
	}
	return 0
}

var File_xgo_tests_gosqltest_gosql_test_proto protoreflect.FileDescriptor

var file_xgo_tests_gosqltest_gosql_test_proto_rawDesc = []byte{
	0x0a, 0x24, 0x78, 0x67, 0x6f, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x73, 0x71,
	0x6c, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x67, 0x6f, 0x73, 0x71, 0x6c, 0x5f, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x6f, 0x73, 0x71, 0x6c, 0x74, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x73, 0x71, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbf, 0x01, 0x0a, 0x05, 0x55, 0x73, 0x65, 0x72, 0x31,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x2c, 0x0a, 0x05, 0x6d, 0x65, 0x74, 0x61, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x67, 0x6f, 0x73, 0x71, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x31, 0x52, 0x05, 0x6d, 0x65, 0x74, 0x61, 0x31, 0x1a, 0x70,
	0x0a, 0x05, 0x4d, 0x65, 0x74, 0x61, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x6d, 0x65, 0x74,
	0x61, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x73, 0x71, 0x6c,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x31,
	0x2e, 0x4d, 0x65, 0x74, 0x61, 0x32, 0x52, 0x05, 0x6d, 0x65, 0x74, 0x61, 0x31, 0x1a, 0x19, 0x0a,
	0x05, 0x4d, 0x65, 0x74, 0x61, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x78, 0x3a, 0x06, 0xca, 0xb2, 0x04, 0x02, 0x0a, 0x00,
	0x3a, 0x06, 0xca, 0xb2, 0x04, 0x02, 0x0a, 0x00, 0x22, 0x2c, 0x0a, 0x05, 0x55, 0x73, 0x65, 0x72,
	0x32, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x3a, 0x13, 0xca, 0xb2, 0x04, 0x0f, 0x12, 0x0d, 0x0a, 0x07, 0x12, 0x01, 0x20, 0x28, 0x01,
	0x30, 0x01, 0x12, 0x02, 0x08, 0x01, 0x22, 0x1f, 0x0a, 0x05, 0x55, 0x73, 0x65, 0x72, 0x33, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x3a,
	0x06, 0xca, 0xb2, 0x04, 0x02, 0x1a, 0x00, 0x22, 0x1f, 0x0a, 0x05, 0x55, 0x73, 0x65, 0x72, 0x34,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x3a, 0x06, 0xca, 0xb2, 0x04, 0x02, 0x22, 0x00, 0x22, 0x1d, 0x0a, 0x05, 0x55, 0x73, 0x65, 0x72,
	0x35, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x3a, 0x04, 0xca, 0xb2, 0x04, 0x00, 0x22, 0x17, 0x0a, 0x05, 0x55, 0x73, 0x65, 0x72, 0x36,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x1b, 0x0a, 0x05, 0x55, 0x73, 0x65, 0x72, 0x37, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x3a, 0x02, 0x10, 0x01, 0x42, 0x11, 0x5a,
	0x0f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x73, 0x71, 0x6c, 0x74, 0x65, 0x73, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xgo_tests_gosqltest_gosql_test_proto_rawDescOnce sync.Once
	file_xgo_tests_gosqltest_gosql_test_proto_rawDescData = file_xgo_tests_gosqltest_gosql_test_proto_rawDesc
)

func file_xgo_tests_gosqltest_gosql_test_proto_rawDescGZIP() []byte {
	file_xgo_tests_gosqltest_gosql_test_proto_rawDescOnce.Do(func() {
		file_xgo_tests_gosqltest_gosql_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_xgo_tests_gosqltest_gosql_test_proto_rawDescData)
	})
	return file_xgo_tests_gosqltest_gosql_test_proto_rawDescData
}

var file_xgo_tests_gosqltest_gosql_test_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_xgo_tests_gosqltest_gosql_test_proto_goTypes = []interface{}{
	(*User1)(nil),             // 0: gosqltest.User1
	(*User2)(nil),             // 1: gosqltest.User2
	(*User3)(nil),             // 2: gosqltest.User3
	(*User4)(nil),             // 3: gosqltest.User4
	(*User5)(nil),             // 4: gosqltest.User5
	(*User6)(nil),             // 5: gosqltest.User6
	(*User7)(nil),             // 6: gosqltest.User7
	(*User1_Meta1)(nil),       // 7: gosqltest.User1.Meta1
	(*User1_Meta1_Meta2)(nil), // 8: gosqltest.User1.Meta1.Meta2
}
var file_xgo_tests_gosqltest_gosql_test_proto_depIdxs = []int32{
	7, // 0: gosqltest.User1.meta1:type_name -> gosqltest.User1.Meta1
	8, // 1: gosqltest.User1.Meta1.meta1:type_name -> gosqltest.User1.Meta1.Meta2
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_xgo_tests_gosqltest_gosql_test_proto_init() }
func file_xgo_tests_gosqltest_gosql_test_proto_init() {
	if File_xgo_tests_gosqltest_gosql_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User5); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User6); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User7); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User1_Meta1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xgo_tests_gosqltest_gosql_test_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User1_Meta1_Meta2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xgo_tests_gosqltest_gosql_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xgo_tests_gosqltest_gosql_test_proto_goTypes,
		DependencyIndexes: file_xgo_tests_gosqltest_gosql_test_proto_depIdxs,
		MessageInfos:      file_xgo_tests_gosqltest_gosql_test_proto_msgTypes,
	}.Build()
	File_xgo_tests_gosqltest_gosql_test_proto = out.File
	file_xgo_tests_gosqltest_gosql_test_proto_rawDesc = nil
	file_xgo_tests_gosqltest_gosql_test_proto_goTypes = nil
	file_xgo_tests_gosqltest_gosql_test_proto_depIdxs = nil
}
