// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: xgo/tests/govalidatorexternal/test_invalid_enum.proto

package govalidatorexternal

import (
	_ "github.com/yu31/protoc-plugin/xgo/pb/pbvalidator"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvalidMessageEnum_Type int32

const (
	InvalidMessageEnum_Cat InvalidMessageEnum_Type = 0
)

// Enum value maps for InvalidMessageEnum_Type.
var (
	InvalidMessageEnum_Type_name = map[int32]string{
		0: "Cat",
	}
	InvalidMessageEnum_Type_value = map[string]int32{
		"Cat": 0,
	}
)

func (x InvalidMessageEnum_Type) Enum() *InvalidMessageEnum_Type {
	p := new(InvalidMessageEnum_Type)
	*p = x
	return p
}

func (x InvalidMessageEnum_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvalidMessageEnum_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_enumTypes[0].Descriptor()
}

func (InvalidMessageEnum_Type) Type() protoreflect.EnumType {
	return &file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_enumTypes[0]
}

func (x InvalidMessageEnum_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvalidMessageEnum_Type.Descriptor instead.
func (InvalidMessageEnum_Type) EnumDescriptor() ([]byte, []int) {
	return file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_rawDescGZIP(), []int{0, 0}
}

type InvalidMessageEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TField1 InvalidMessageEnum_Type `protobuf:"varint,1,opt,name=t_field1,json=tField1,proto3,enum=godefaultstest.InvalidMessageEnum_Type" json:"t_field1,omitempty"`
}

func (x *InvalidMessageEnum) Reset() {
	*x = InvalidMessageEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvalidMessageEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidMessageEnum) ProtoMessage() {}

func (x *InvalidMessageEnum) ProtoReflect() protoreflect.Message {
	mi := &file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidMessageEnum.ProtoReflect.Descriptor instead.
func (*InvalidMessageEnum) Descriptor() ([]byte, []int) {
	return file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_rawDescGZIP(), []int{0}
}

func (x *InvalidMessageEnum) GetTField1() InvalidMessageEnum_Type {
	if x != nil {
		return x.TField1
	}
	return InvalidMessageEnum_Cat
}

var File_xgo_tests_govalidatorexternal_test_invalid_enum_proto protoreflect.FileDescriptor

var file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_rawDesc = []byte{
	0x0a, 0x35, 0x78, 0x67, 0x6f, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x74, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x65, 0x6e, 0x75,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x67, 0x6f, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x73, 0x74, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x74,
	0x0a, 0x12, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x45, 0x6e, 0x75, 0x6d, 0x12, 0x4d, 0x0a, 0x08, 0x74, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x31,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x67, 0x6f, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x73, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x42,
	0x09, 0xe2, 0xdf, 0x1f, 0x05, 0x12, 0x03, 0xda, 0x01, 0x00, 0x52, 0x07, 0x74, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x31, 0x22, 0x0f, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x43,
	0x61, 0x74, 0x10, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x67, 0x6f,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_rawDescOnce sync.Once
	file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_rawDescData = file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_rawDesc
)

func file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_rawDescGZIP() []byte {
	file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_rawDescOnce.Do(func() {
		file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_rawDescData)
	})
	return file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_rawDescData
}

var file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_goTypes = []interface{}{
	(InvalidMessageEnum_Type)(0), // 0: godefaultstest.InvalidMessageEnum.Type
	(*InvalidMessageEnum)(nil),   // 1: godefaultstest.InvalidMessageEnum
}
var file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_depIdxs = []int32{
	0, // 0: godefaultstest.InvalidMessageEnum.t_field1:type_name -> godefaultstest.InvalidMessageEnum.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_init() }
func file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_init() {
	if File_xgo_tests_govalidatorexternal_test_invalid_enum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvalidMessageEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_goTypes,
		DependencyIndexes: file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_depIdxs,
		EnumInfos:         file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_enumTypes,
		MessageInfos:      file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_msgTypes,
	}.Build()
	File_xgo_tests_govalidatorexternal_test_invalid_enum_proto = out.File
	file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_rawDesc = nil
	file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_goTypes = nil
	file_xgo_tests_govalidatorexternal_test_invalid_enum_proto_depIdxs = nil
}
