// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: xgo/tests/govalidatorexternal/test_invalid_map.proto

package govalidatorexternal

import (
	_ "github.com/yu31/protoc-plugin/xgo/pb/pbvalidator"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvalidMessageMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TMapString map[string]string `protobuf:"bytes,1,rep,name=t_map_string,json=tMapString,proto3" json:"t_map_string,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *InvalidMessageMap) Reset() {
	*x = InvalidMessageMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xgo_tests_govalidatorexternal_test_invalid_map_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvalidMessageMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidMessageMap) ProtoMessage() {}

func (x *InvalidMessageMap) ProtoReflect() protoreflect.Message {
	mi := &file_xgo_tests_govalidatorexternal_test_invalid_map_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidMessageMap.ProtoReflect.Descriptor instead.
func (*InvalidMessageMap) Descriptor() ([]byte, []int) {
	return file_xgo_tests_govalidatorexternal_test_invalid_map_proto_rawDescGZIP(), []int{0}
}

func (x *InvalidMessageMap) GetTMapString() map[string]string {
	if x != nil {
		return x.TMapString
	}
	return nil
}

var File_xgo_tests_govalidatorexternal_test_invalid_map_proto protoreflect.FileDescriptor

var file_xgo_tests_govalidatorexternal_test_invalid_map_proto_rawDesc = []byte{
	0x0a, 0x34, 0x78, 0x67, 0x6f, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x74, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x6d, 0x61, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x67, 0x6f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x73, 0x74, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb4, 0x01,
	0x0a, 0x11, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x4d, 0x61, 0x70, 0x12, 0x60, 0x0a, 0x0c, 0x74, 0x5f, 0x6d, 0x61, 0x70, 0x5f, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x67, 0x6f, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4d, 0x61, 0x70, 0x2e, 0x54, 0x4d, 0x61,
	0x70, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x42, 0x0b, 0xe2, 0xdf,
	0x1f, 0x07, 0x12, 0x05, 0xf2, 0x01, 0x02, 0x10, 0x01, 0x52, 0x0a, 0x74, 0x4d, 0x61, 0x70, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x3d, 0x0a, 0x0f, 0x54, 0x4d, 0x61, 0x70, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x42, 0x1b, 0x5a, 0x19, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x67, 0x6f,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xgo_tests_govalidatorexternal_test_invalid_map_proto_rawDescOnce sync.Once
	file_xgo_tests_govalidatorexternal_test_invalid_map_proto_rawDescData = file_xgo_tests_govalidatorexternal_test_invalid_map_proto_rawDesc
)

func file_xgo_tests_govalidatorexternal_test_invalid_map_proto_rawDescGZIP() []byte {
	file_xgo_tests_govalidatorexternal_test_invalid_map_proto_rawDescOnce.Do(func() {
		file_xgo_tests_govalidatorexternal_test_invalid_map_proto_rawDescData = protoimpl.X.CompressGZIP(file_xgo_tests_govalidatorexternal_test_invalid_map_proto_rawDescData)
	})
	return file_xgo_tests_govalidatorexternal_test_invalid_map_proto_rawDescData
}

var file_xgo_tests_govalidatorexternal_test_invalid_map_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_xgo_tests_govalidatorexternal_test_invalid_map_proto_goTypes = []interface{}{
	(*InvalidMessageMap)(nil), // 0: godefaultstest.InvalidMessageMap
	nil,                       // 1: godefaultstest.InvalidMessageMap.TMapStringEntry
}
var file_xgo_tests_govalidatorexternal_test_invalid_map_proto_depIdxs = []int32{
	1, // 0: godefaultstest.InvalidMessageMap.t_map_string:type_name -> godefaultstest.InvalidMessageMap.TMapStringEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_xgo_tests_govalidatorexternal_test_invalid_map_proto_init() }
func file_xgo_tests_govalidatorexternal_test_invalid_map_proto_init() {
	if File_xgo_tests_govalidatorexternal_test_invalid_map_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xgo_tests_govalidatorexternal_test_invalid_map_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvalidMessageMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xgo_tests_govalidatorexternal_test_invalid_map_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xgo_tests_govalidatorexternal_test_invalid_map_proto_goTypes,
		DependencyIndexes: file_xgo_tests_govalidatorexternal_test_invalid_map_proto_depIdxs,
		MessageInfos:      file_xgo_tests_govalidatorexternal_test_invalid_map_proto_msgTypes,
	}.Build()
	File_xgo_tests_govalidatorexternal_test_invalid_map_proto = out.File
	file_xgo_tests_govalidatorexternal_test_invalid_map_proto_rawDesc = nil
	file_xgo_tests_govalidatorexternal_test_invalid_map_proto_goTypes = nil
	file_xgo_tests_govalidatorexternal_test_invalid_map_proto_depIdxs = nil
}
