# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gosql.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/gosql.proto\x12\x05gosql\x1a google/protobuf/descriptor.proto\"\x9f\x01\n\tSerialize\x12\x1b\n\x04json\x18\x01 \x01(\x0b\x32\x0b.gosql.JSONH\x00\x12%\n\tprotojson\x18\x02 \x01(\x0b\x32\x10.gosql.ProtoJSONH\x00\x12\x1d\n\x05proto\x18\x03 \x01(\x0b\x32\x0c.gosql.ProtoH\x00\x12%\n\tgogoproto\x18\x04 \x01(\x0b\x32\x10.gosql.GoGoProtoH\x00\x42\x08\n\x06\x46ormat\"\x06\n\x04JSON\"\xc9\x02\n\tProtoJSON\x12\x30\n\x07marshal\x18\x01 \x01(\x0b\x32\x1f.gosql.ProtoJSON.MarshalOptions\x12\x34\n\tunmarshal\x18\x02 \x01(\x0b\x32!.gosql.ProtoJSON.UnmarshalOptions\x1a\x91\x01\n\x0eMarshalOptions\x12\x11\n\tMultiline\x18\x01 \x01(\x08\x12\x0e\n\x06Indent\x18\x02 \x01(\t\x12\x14\n\x0c\x41llowPartial\x18\x03 \x01(\x08\x12\x15\n\rUseProtoNames\x18\x04 \x01(\x08\x12\x16\n\x0eUseEnumNumbers\x18\x05 \x01(\x08\x12\x17\n\x0f\x45mitUnpopulated\x18\x06 \x01(\x08\x1a@\n\x10UnmarshalOptions\x12\x14\n\x0c\x41llowPartial\x18\x01 \x01(\x08\x12\x16\n\x0e\x44iscardUnknown\x18\x02 \x01(\x08\"\x8e\x02\n\x05Proto\x12,\n\x07marshal\x18\x01 \x01(\x0b\x32\x1b.gosql.Proto.MarshalOptions\x12\x30\n\tunmarshal\x18\x02 \x01(\x0b\x32\x1d.gosql.Proto.UnmarshalOptions\x1aT\n\x0eMarshalOptions\x12\x14\n\x0c\x41llowPartial\x18\x01 \x01(\x08\x12\x15\n\rDeterministic\x18\x02 \x01(\x08\x12\x15\n\rUseCachedSize\x18\x03 \x01(\x08\x1aO\n\x10UnmarshalOptions\x12\r\n\x05Merge\x18\x01 \x01(\x08\x12\x14\n\x0c\x41llowPartial\x18\x02 \x01(\x08\x12\x16\n\x0e\x44iscardUnknown\x18\x03 \x01(\x08\"\x0b\n\tGoGoProto:E\n\tserialize\x12\x1f.google.protobuf.MessageOptions\x18\xa9\x46 \x01(\x0b\x32\x10.gosql.SerializeB[\n io.github.yu31.protoc.pb.pbgosqlB\x07PBGoSQLP\x00Z,github.com/yu31/protoc-plugin/xgo/pb/pbgosqlb\x06proto3')


SERIALIZE_FIELD_NUMBER = 9001
serialize = DESCRIPTOR.extensions_by_name['serialize']

_SERIALIZE = DESCRIPTOR.message_types_by_name['Serialize']
_JSON = DESCRIPTOR.message_types_by_name['JSON']
_PROTOJSON = DESCRIPTOR.message_types_by_name['ProtoJSON']
_PROTOJSON_MARSHALOPTIONS = _PROTOJSON.nested_types_by_name['MarshalOptions']
_PROTOJSON_UNMARSHALOPTIONS = _PROTOJSON.nested_types_by_name['UnmarshalOptions']
_PROTO = DESCRIPTOR.message_types_by_name['Proto']
_PROTO_MARSHALOPTIONS = _PROTO.nested_types_by_name['MarshalOptions']
_PROTO_UNMARSHALOPTIONS = _PROTO.nested_types_by_name['UnmarshalOptions']
_GOGOPROTO = DESCRIPTOR.message_types_by_name['GoGoProto']
Serialize = _reflection.GeneratedProtocolMessageType('Serialize', (_message.Message,), {
  'DESCRIPTOR' : _SERIALIZE,
  '__module__' : 'proto.gosql_pb2'
  # @@protoc_insertion_point(class_scope:gosql.Serialize)
  })
_sym_db.RegisterMessage(Serialize)

JSON = _reflection.GeneratedProtocolMessageType('JSON', (_message.Message,), {
  'DESCRIPTOR' : _JSON,
  '__module__' : 'proto.gosql_pb2'
  # @@protoc_insertion_point(class_scope:gosql.JSON)
  })
_sym_db.RegisterMessage(JSON)

ProtoJSON = _reflection.GeneratedProtocolMessageType('ProtoJSON', (_message.Message,), {

  'MarshalOptions' : _reflection.GeneratedProtocolMessageType('MarshalOptions', (_message.Message,), {
    'DESCRIPTOR' : _PROTOJSON_MARSHALOPTIONS,
    '__module__' : 'proto.gosql_pb2'
    # @@protoc_insertion_point(class_scope:gosql.ProtoJSON.MarshalOptions)
    })
  ,

  'UnmarshalOptions' : _reflection.GeneratedProtocolMessageType('UnmarshalOptions', (_message.Message,), {
    'DESCRIPTOR' : _PROTOJSON_UNMARSHALOPTIONS,
    '__module__' : 'proto.gosql_pb2'
    # @@protoc_insertion_point(class_scope:gosql.ProtoJSON.UnmarshalOptions)
    })
  ,
  'DESCRIPTOR' : _PROTOJSON,
  '__module__' : 'proto.gosql_pb2'
  # @@protoc_insertion_point(class_scope:gosql.ProtoJSON)
  })
_sym_db.RegisterMessage(ProtoJSON)
_sym_db.RegisterMessage(ProtoJSON.MarshalOptions)
_sym_db.RegisterMessage(ProtoJSON.UnmarshalOptions)

Proto = _reflection.GeneratedProtocolMessageType('Proto', (_message.Message,), {

  'MarshalOptions' : _reflection.GeneratedProtocolMessageType('MarshalOptions', (_message.Message,), {
    'DESCRIPTOR' : _PROTO_MARSHALOPTIONS,
    '__module__' : 'proto.gosql_pb2'
    # @@protoc_insertion_point(class_scope:gosql.Proto.MarshalOptions)
    })
  ,

  'UnmarshalOptions' : _reflection.GeneratedProtocolMessageType('UnmarshalOptions', (_message.Message,), {
    'DESCRIPTOR' : _PROTO_UNMARSHALOPTIONS,
    '__module__' : 'proto.gosql_pb2'
    # @@protoc_insertion_point(class_scope:gosql.Proto.UnmarshalOptions)
    })
  ,
  'DESCRIPTOR' : _PROTO,
  '__module__' : 'proto.gosql_pb2'
  # @@protoc_insertion_point(class_scope:gosql.Proto)
  })
_sym_db.RegisterMessage(Proto)
_sym_db.RegisterMessage(Proto.MarshalOptions)
_sym_db.RegisterMessage(Proto.UnmarshalOptions)

GoGoProto = _reflection.GeneratedProtocolMessageType('GoGoProto', (_message.Message,), {
  'DESCRIPTOR' : _GOGOPROTO,
  '__module__' : 'proto.gosql_pb2'
  # @@protoc_insertion_point(class_scope:gosql.GoGoProto)
  })
_sym_db.RegisterMessage(GoGoProto)

if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(serialize)

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n io.github.yu31.protoc.pb.pbgosqlB\007PBGoSQLP\000Z,github.com/yu31/protoc-plugin/xgo/pb/pbgosql'
  _SERIALIZE._serialized_start=63
  _SERIALIZE._serialized_end=222
  _JSON._serialized_start=224
  _JSON._serialized_end=230
  _PROTOJSON._serialized_start=233
  _PROTOJSON._serialized_end=562
  _PROTOJSON_MARSHALOPTIONS._serialized_start=351
  _PROTOJSON_MARSHALOPTIONS._serialized_end=496
  _PROTOJSON_UNMARSHALOPTIONS._serialized_start=498
  _PROTOJSON_UNMARSHALOPTIONS._serialized_end=562
  _PROTO._serialized_start=565
  _PROTO._serialized_end=835
  _PROTO_MARSHALOPTIONS._serialized_start=670
  _PROTO_MARSHALOPTIONS._serialized_end=754
  _PROTO_UNMARSHALOPTIONS._serialized_start=756
  _PROTO_UNMARSHALOPTIONS._serialized_end=835
  _GOGOPROTO._serialized_start=837
  _GOGOPROTO._serialized_end=848
# @@protoc_insertion_point(module_scope)
