// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: xgo/tests/gojsonexternal/gojson_external.proto

package gojsonexternal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExternalEnum1 int32

const (
	ExternalEnum1_Monday    ExternalEnum1 = 0
	ExternalEnum1_Tuesday   ExternalEnum1 = 1
	ExternalEnum1_Wednesday ExternalEnum1 = 2
	ExternalEnum1_Thursday  ExternalEnum1 = 3
	ExternalEnum1_Friday    ExternalEnum1 = 4
	ExternalEnum1_Saturday  ExternalEnum1 = 5
	ExternalEnum1_Sunday    ExternalEnum1 = 6
)

// Enum value maps for ExternalEnum1.
var (
	ExternalEnum1_name = map[int32]string{
		0: "Monday",
		1: "Tuesday",
		2: "Wednesday",
		3: "Thursday",
		4: "Friday",
		5: "Saturday",
		6: "Sunday",
	}
	ExternalEnum1_value = map[string]int32{
		"Monday":    0,
		"Tuesday":   1,
		"Wednesday": 2,
		"Thursday":  3,
		"Friday":    4,
		"Saturday":  5,
		"Sunday":    6,
	}
)

func (x ExternalEnum1) Enum() *ExternalEnum1 {
	p := new(ExternalEnum1)
	*p = x
	return p
}

func (x ExternalEnum1) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExternalEnum1) Descriptor() protoreflect.EnumDescriptor {
	return file_xgo_tests_gojsonexternal_gojson_external_proto_enumTypes[0].Descriptor()
}

func (ExternalEnum1) Type() protoreflect.EnumType {
	return &file_xgo_tests_gojsonexternal_gojson_external_proto_enumTypes[0]
}

func (x ExternalEnum1) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExternalEnum1.Descriptor instead.
func (ExternalEnum1) EnumDescriptor() ([]byte, []int) {
	return file_xgo_tests_gojsonexternal_gojson_external_proto_rawDescGZIP(), []int{0}
}

type ExternalMessage1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip1 string `protobuf:"bytes,1,opt,name=ip1,proto3" json:"ip1,omitempty"`
	Ip2 string `protobuf:"bytes,2,opt,name=ip2,proto3" json:"ip2,omitempty"`
	Ip3 string `protobuf:"bytes,3,opt,name=ip3,proto3" json:"ip3,omitempty"`
}

func (x *ExternalMessage1) Reset() {
	*x = ExternalMessage1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xgo_tests_gojsonexternal_gojson_external_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalMessage1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalMessage1) ProtoMessage() {}

func (x *ExternalMessage1) ProtoReflect() protoreflect.Message {
	mi := &file_xgo_tests_gojsonexternal_gojson_external_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalMessage1.ProtoReflect.Descriptor instead.
func (*ExternalMessage1) Descriptor() ([]byte, []int) {
	return file_xgo_tests_gojsonexternal_gojson_external_proto_rawDescGZIP(), []int{0}
}

func (x *ExternalMessage1) GetIp1() string {
	if x != nil {
		return x.Ip1
	}
	return ""
}

func (x *ExternalMessage1) GetIp2() string {
	if x != nil {
		return x.Ip2
	}
	return ""
}

func (x *ExternalMessage1) GetIp3() string {
	if x != nil {
		return x.Ip3
	}
	return ""
}

var File_xgo_tests_gojsonexternal_gojson_external_proto protoreflect.FileDescriptor

var file_xgo_tests_gojsonexternal_gojson_external_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x78, 0x67, 0x6f, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x6a, 0x73,
	0x6f, 0x6e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x6f, 0x6a, 0x73, 0x6f,
	0x6e, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x67, 0x6f, 0x6a, 0x73, 0x6f, 0x6e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x22, 0x48, 0x0a, 0x10, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x70, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x69, 0x70, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x70, 0x32, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x70, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x70, 0x33, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x70, 0x33, 0x2a, 0x6b, 0x0a, 0x0d, 0x45, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x31, 0x12, 0x0a, 0x0a, 0x06, 0x4d,
	0x6f, 0x6e, 0x64, 0x61, 0x79, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x75, 0x65, 0x73, 0x64,
	0x61, 0x79, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x57, 0x65, 0x64, 0x6e, 0x65, 0x73, 0x64, 0x61,
	0x79, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x68, 0x75, 0x72, 0x73, 0x64, 0x61, 0x79, 0x10,
	0x03, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x72, 0x69, 0x64, 0x61, 0x79, 0x10, 0x04, 0x12, 0x0c, 0x0a,
	0x08, 0x53, 0x61, 0x74, 0x75, 0x72, 0x64, 0x61, 0x79, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x53,
	0x75, 0x6e, 0x64, 0x61, 0x79, 0x10, 0x06, 0x42, 0x47, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x75, 0x33, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x2d, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x78, 0x67, 0x6f, 0x2f, 0x74, 0x65, 0x73,
	0x74, 0x73, 0x2f, 0x67, 0x6f, 0x6a, 0x73, 0x6f, 0x6e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x3b, 0x67, 0x6f, 0x6a, 0x73, 0x6f, 0x6e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xgo_tests_gojsonexternal_gojson_external_proto_rawDescOnce sync.Once
	file_xgo_tests_gojsonexternal_gojson_external_proto_rawDescData = file_xgo_tests_gojsonexternal_gojson_external_proto_rawDesc
)

func file_xgo_tests_gojsonexternal_gojson_external_proto_rawDescGZIP() []byte {
	file_xgo_tests_gojsonexternal_gojson_external_proto_rawDescOnce.Do(func() {
		file_xgo_tests_gojsonexternal_gojson_external_proto_rawDescData = protoimpl.X.CompressGZIP(file_xgo_tests_gojsonexternal_gojson_external_proto_rawDescData)
	})
	return file_xgo_tests_gojsonexternal_gojson_external_proto_rawDescData
}

var file_xgo_tests_gojsonexternal_gojson_external_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xgo_tests_gojsonexternal_gojson_external_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_xgo_tests_gojsonexternal_gojson_external_proto_goTypes = []interface{}{
	(ExternalEnum1)(0),       // 0: gojsonexternal.ExternalEnum1
	(*ExternalMessage1)(nil), // 1: gojsonexternal.ExternalMessage1
}
var file_xgo_tests_gojsonexternal_gojson_external_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xgo_tests_gojsonexternal_gojson_external_proto_init() }
func file_xgo_tests_gojsonexternal_gojson_external_proto_init() {
	if File_xgo_tests_gojsonexternal_gojson_external_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xgo_tests_gojsonexternal_gojson_external_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalMessage1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xgo_tests_gojsonexternal_gojson_external_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xgo_tests_gojsonexternal_gojson_external_proto_goTypes,
		DependencyIndexes: file_xgo_tests_gojsonexternal_gojson_external_proto_depIdxs,
		EnumInfos:         file_xgo_tests_gojsonexternal_gojson_external_proto_enumTypes,
		MessageInfos:      file_xgo_tests_gojsonexternal_gojson_external_proto_msgTypes,
	}.Build()
	File_xgo_tests_gojsonexternal_gojson_external_proto = out.File
	file_xgo_tests_gojsonexternal_gojson_external_proto_rawDesc = nil
	file_xgo_tests_gojsonexternal_gojson_external_proto_goTypes = nil
	file_xgo_tests_gojsonexternal_gojson_external_proto_depIdxs = nil
}
