// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: xgo/tests/gosqlignore/gosql_ignore.proto

package gosqlignore

import (
	_ "github.com/yu31/protoc-plugin/xgo/pb/pbgosql"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Args struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tt string `protobuf:"bytes,1,opt,name=tt,proto3" json:"tt,omitempty"`
}

func (x *Args) Reset() {
	*x = Args{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xgo_tests_gosqlignore_gosql_ignore_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Args) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Args) ProtoMessage() {}

func (x *Args) ProtoReflect() protoreflect.Message {
	mi := &file_xgo_tests_gosqlignore_gosql_ignore_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Args.ProtoReflect.Descriptor instead.
func (*Args) Descriptor() ([]byte, []int) {
	return file_xgo_tests_gosqlignore_gosql_ignore_proto_rawDescGZIP(), []int{0}
}

func (x *Args) GetTt() string {
	if x != nil {
		return x.Tt
	}
	return ""
}

var File_xgo_tests_gosqlignore_gosql_ignore_proto protoreflect.FileDescriptor

var file_xgo_tests_gosqlignore_gosql_ignore_proto_rawDesc = []byte{
	0x0a, 0x28, 0x78, 0x67, 0x6f, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x73, 0x71,
	0x6c, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x2f, 0x67, 0x6f, 0x73, 0x71, 0x6c, 0x5f, 0x69, 0x67,
	0x6e, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x6f, 0x73, 0x71,
	0x6c, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x1a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67,
	0x6f, 0x73, 0x71, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1c, 0x0a, 0x04, 0x41, 0x72,
	0x67, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x74, 0x74, 0x3a, 0x04, 0xca, 0xb2, 0x04, 0x00, 0x32, 0x36, 0x0a, 0x02, 0x53, 0x31, 0x12, 0x30,
	0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x67, 0x6f, 0x73, 0x71, 0x6c,
	0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x2e, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x11, 0x2e, 0x67, 0x6f,
	0x73, 0x71, 0x6c, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x2e, 0x41, 0x72, 0x67, 0x73, 0x22, 0x00,
	0x42, 0x13, 0x5a, 0x11, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x73, 0x71, 0x6c, 0x69,
	0x67, 0x6e, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xgo_tests_gosqlignore_gosql_ignore_proto_rawDescOnce sync.Once
	file_xgo_tests_gosqlignore_gosql_ignore_proto_rawDescData = file_xgo_tests_gosqlignore_gosql_ignore_proto_rawDesc
)

func file_xgo_tests_gosqlignore_gosql_ignore_proto_rawDescGZIP() []byte {
	file_xgo_tests_gosqlignore_gosql_ignore_proto_rawDescOnce.Do(func() {
		file_xgo_tests_gosqlignore_gosql_ignore_proto_rawDescData = protoimpl.X.CompressGZIP(file_xgo_tests_gosqlignore_gosql_ignore_proto_rawDescData)
	})
	return file_xgo_tests_gosqlignore_gosql_ignore_proto_rawDescData
}

var file_xgo_tests_gosqlignore_gosql_ignore_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_xgo_tests_gosqlignore_gosql_ignore_proto_goTypes = []interface{}{
	(*Args)(nil), // 0: gosqlignore.Args
}
var file_xgo_tests_gosqlignore_gosql_ignore_proto_depIdxs = []int32{
	0, // 0: gosqlignore.S1.Create:input_type -> gosqlignore.Args
	0, // 1: gosqlignore.S1.Create:output_type -> gosqlignore.Args
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xgo_tests_gosqlignore_gosql_ignore_proto_init() }
func file_xgo_tests_gosqlignore_gosql_ignore_proto_init() {
	if File_xgo_tests_gosqlignore_gosql_ignore_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xgo_tests_gosqlignore_gosql_ignore_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Args); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xgo_tests_gosqlignore_gosql_ignore_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xgo_tests_gosqlignore_gosql_ignore_proto_goTypes,
		DependencyIndexes: file_xgo_tests_gosqlignore_gosql_ignore_proto_depIdxs,
		MessageInfos:      file_xgo_tests_gosqlignore_gosql_ignore_proto_msgTypes,
	}.Build()
	File_xgo_tests_gosqlignore_gosql_ignore_proto = out.File
	file_xgo_tests_gosqlignore_gosql_ignore_proto_rawDesc = nil
	file_xgo_tests_gosqlignore_gosql_ignore_proto_goTypes = nil
	file_xgo_tests_gosqlignore_gosql_ignore_proto_depIdxs = nil
}
