// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: defaults.proto

package com.github.yu31.protoc.pbdefaults;

public final class PBDefaults {
  private PBDefaults() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.github.yu31.protoc.pbdefaults.PBDefaults.field);
    registry.add(com.github.yu31.protoc.pbdefaults.PBDefaults.oneof);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FieldOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:defaults.FieldOptions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Set default value for field that types includes:
     * string, enum, bool,
     * int32, int64, sint32, sint64, sfixed32, sfixed64,
     * uint32, uint64,fixed32, fixed64.
     * </pre>
     *
     * <code>optional string basic = 101;</code>
     * @return Whether the basic field is set.
     */
    boolean hasBasic();
    /**
     * <pre>
     * Set default value for field that types includes:
     * string, enum, bool,
     * int32, int64, sint32, sint64, sfixed32, sfixed64,
     * uint32, uint64,fixed32, fixed64.
     * </pre>
     *
     * <code>optional string basic = 101;</code>
     * @return The basic.
     */
    java.lang.String getBasic();
    /**
     * <pre>
     * Set default value for field that types includes:
     * string, enum, bool,
     * int32, int64, sint32, sint64, sfixed32, sfixed64,
     * uint32, uint64,fixed32, fixed64.
     * </pre>
     *
     * <code>optional string basic = 101;</code>
     * @return The bytes for basic.
     */
    com.google.protobuf.ByteString
        getBasicBytes();

    /**
     * <pre>
     * Set default value for field of types repeated.
     * </pre>
     *
     * <code>repeated string array = 102;</code>
     * @return A list containing the array.
     */
    java.util.List<java.lang.String>
        getArrayList();
    /**
     * <pre>
     * Set default value for field of types repeated.
     * </pre>
     *
     * <code>repeated string array = 102;</code>
     * @return The count of array.
     */
    int getArrayCount();
    /**
     * <pre>
     * Set default value for field of types repeated.
     * </pre>
     *
     * <code>repeated string array = 102;</code>
     * @param index The index of the element to return.
     * @return The array at the given index.
     */
    java.lang.String getArray(int index);
    /**
     * <pre>
     * Set default value for field of types repeated.
     * </pre>
     *
     * <code>repeated string array = 102;</code>
     * @param index The index of the value to return.
     * @return The bytes of the array at the given index.
     */
    com.google.protobuf.ByteString
        getArrayBytes(int index);

    /**
     * <pre>
     * Set default value for field of types map.
     * </pre>
     *
     * <code>map&lt;string, string&gt; map = 103;</code>
     */
    int getMapCount();
    /**
     * <pre>
     * Set default value for field of types map.
     * </pre>
     *
     * <code>map&lt;string, string&gt; map = 103;</code>
     */
    boolean containsMap(
        java.lang.String key);
    /**
     * Use {@link #getMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getMap();
    /**
     * <pre>
     * Set default value for field of types map.
     * </pre>
     *
     * <code>map&lt;string, string&gt; map = 103;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getMapMap();
    /**
     * <pre>
     * Set default value for field of types map.
     * </pre>
     *
     * <code>map&lt;string, string&gt; map = 103;</code>
     */

    java.lang.String getMapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <pre>
     * Set default value for field of types map.
     * </pre>
     *
     * <code>map&lt;string, string&gt; map = 103;</code>
     */

    java.lang.String getMapOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code defaults.FieldOptions}
   */
  public static final class FieldOptions extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:defaults.FieldOptions)
      FieldOptionsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FieldOptions.newBuilder() to construct.
    private FieldOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FieldOptions() {
      basic_ = "";
      array_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FieldOptions();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FieldOptions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 810: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              basic_ = s;
              break;
            }
            case 818: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                array_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              array_.add(s);
              break;
            }
            case 826: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                map_ = com.google.protobuf.MapField.newMapField(
                    MapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              map__ = input.readMessage(
                  MapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              map_.getMutableMap().put(
                  map__.getKey(), map__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          array_ = array_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.yu31.protoc.pbdefaults.PBDefaults.internal_static_defaults_FieldOptions_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 103:
          return internalGetMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.yu31.protoc.pbdefaults.PBDefaults.internal_static_defaults_FieldOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions.class, com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions.Builder.class);
    }

    private int bitField0_;
    public static final int BASIC_FIELD_NUMBER = 101;
    private volatile java.lang.Object basic_;
    /**
     * <pre>
     * Set default value for field that types includes:
     * string, enum, bool,
     * int32, int64, sint32, sint64, sfixed32, sfixed64,
     * uint32, uint64,fixed32, fixed64.
     * </pre>
     *
     * <code>optional string basic = 101;</code>
     * @return Whether the basic field is set.
     */
    @java.lang.Override
    public boolean hasBasic() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Set default value for field that types includes:
     * string, enum, bool,
     * int32, int64, sint32, sint64, sfixed32, sfixed64,
     * uint32, uint64,fixed32, fixed64.
     * </pre>
     *
     * <code>optional string basic = 101;</code>
     * @return The basic.
     */
    @java.lang.Override
    public java.lang.String getBasic() {
      java.lang.Object ref = basic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        basic_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Set default value for field that types includes:
     * string, enum, bool,
     * int32, int64, sint32, sint64, sfixed32, sfixed64,
     * uint32, uint64,fixed32, fixed64.
     * </pre>
     *
     * <code>optional string basic = 101;</code>
     * @return The bytes for basic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBasicBytes() {
      java.lang.Object ref = basic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        basic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARRAY_FIELD_NUMBER = 102;
    private com.google.protobuf.LazyStringList array_;
    /**
     * <pre>
     * Set default value for field of types repeated.
     * </pre>
     *
     * <code>repeated string array = 102;</code>
     * @return A list containing the array.
     */
    public com.google.protobuf.ProtocolStringList
        getArrayList() {
      return array_;
    }
    /**
     * <pre>
     * Set default value for field of types repeated.
     * </pre>
     *
     * <code>repeated string array = 102;</code>
     * @return The count of array.
     */
    public int getArrayCount() {
      return array_.size();
    }
    /**
     * <pre>
     * Set default value for field of types repeated.
     * </pre>
     *
     * <code>repeated string array = 102;</code>
     * @param index The index of the element to return.
     * @return The array at the given index.
     */
    public java.lang.String getArray(int index) {
      return array_.get(index);
    }
    /**
     * <pre>
     * Set default value for field of types repeated.
     * </pre>
     *
     * <code>repeated string array = 102;</code>
     * @param index The index of the value to return.
     * @return The bytes of the array at the given index.
     */
    public com.google.protobuf.ByteString
        getArrayBytes(int index) {
      return array_.getByteString(index);
    }

    public static final int MAP_FIELD_NUMBER = 103;
    private static final class MapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.github.yu31.protoc.pbdefaults.PBDefaults.internal_static_defaults_FieldOptions_MapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> map_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMap() {
      if (map_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapDefaultEntryHolder.defaultEntry);
      }
      return map_;
    }

    public int getMapCount() {
      return internalGetMap().getMap().size();
    }
    /**
     * <pre>
     * Set default value for field of types map.
     * </pre>
     *
     * <code>map&lt;string, string&gt; map = 103;</code>
     */

    @java.lang.Override
    public boolean containsMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMap() {
      return getMapMap();
    }
    /**
     * <pre>
     * Set default value for field of types map.
     * </pre>
     *
     * <code>map&lt;string, string&gt; map = 103;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getMapMap() {
      return internalGetMap().getMap();
    }
    /**
     * <pre>
     * Set default value for field of types map.
     * </pre>
     *
     * <code>map&lt;string, string&gt; map = 103;</code>
     */
    @java.lang.Override

    public java.lang.String getMapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Set default value for field of types map.
     * </pre>
     *
     * <code>map&lt;string, string&gt; map = 103;</code>
     */
    @java.lang.Override

    public java.lang.String getMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 101, basic_);
      }
      for (int i = 0; i < array_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 102, array_.getRaw(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMap(),
          MapDefaultEntryHolder.defaultEntry,
          103);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(101, basic_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < array_.size(); i++) {
          dataSize += computeStringSizeNoTag(array_.getRaw(i));
        }
        size += dataSize;
        size += 2 * getArrayList().size();
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        map__ = MapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(103, map__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions)) {
        return super.equals(obj);
      }
      com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions other = (com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions) obj;

      if (hasBasic() != other.hasBasic()) return false;
      if (hasBasic()) {
        if (!getBasic()
            .equals(other.getBasic())) return false;
      }
      if (!getArrayList()
          .equals(other.getArrayList())) return false;
      if (!internalGetMap().equals(
          other.internalGetMap())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBasic()) {
        hash = (37 * hash) + BASIC_FIELD_NUMBER;
        hash = (53 * hash) + getBasic().hashCode();
      }
      if (getArrayCount() > 0) {
        hash = (37 * hash) + ARRAY_FIELD_NUMBER;
        hash = (53 * hash) + getArrayList().hashCode();
      }
      if (!internalGetMap().getMap().isEmpty()) {
        hash = (37 * hash) + MAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMap().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code defaults.FieldOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:defaults.FieldOptions)
        com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.yu31.protoc.pbdefaults.PBDefaults.internal_static_defaults_FieldOptions_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 103:
            return internalGetMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 103:
            return internalGetMutableMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.yu31.protoc.pbdefaults.PBDefaults.internal_static_defaults_FieldOptions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions.class, com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions.Builder.class);
      }

      // Construct using com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        basic_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        array_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutableMap().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.yu31.protoc.pbdefaults.PBDefaults.internal_static_defaults_FieldOptions_descriptor;
      }

      @java.lang.Override
      public com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions getDefaultInstanceForType() {
        return com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions build() {
        com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions buildPartial() {
        com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions result = new com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.basic_ = basic_;
        if (((bitField0_ & 0x00000002) != 0)) {
          array_ = array_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.array_ = array_;
        result.map_ = internalGetMap();
        result.map_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions) {
          return mergeFrom((com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions other) {
        if (other == com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions.getDefaultInstance()) return this;
        if (other.hasBasic()) {
          bitField0_ |= 0x00000001;
          basic_ = other.basic_;
          onChanged();
        }
        if (!other.array_.isEmpty()) {
          if (array_.isEmpty()) {
            array_ = other.array_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureArrayIsMutable();
            array_.addAll(other.array_);
          }
          onChanged();
        }
        internalGetMutableMap().mergeFrom(
            other.internalGetMap());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object basic_ = "";
      /**
       * <pre>
       * Set default value for field that types includes:
       * string, enum, bool,
       * int32, int64, sint32, sint64, sfixed32, sfixed64,
       * uint32, uint64,fixed32, fixed64.
       * </pre>
       *
       * <code>optional string basic = 101;</code>
       * @return Whether the basic field is set.
       */
      public boolean hasBasic() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Set default value for field that types includes:
       * string, enum, bool,
       * int32, int64, sint32, sint64, sfixed32, sfixed64,
       * uint32, uint64,fixed32, fixed64.
       * </pre>
       *
       * <code>optional string basic = 101;</code>
       * @return The basic.
       */
      public java.lang.String getBasic() {
        java.lang.Object ref = basic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          basic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Set default value for field that types includes:
       * string, enum, bool,
       * int32, int64, sint32, sint64, sfixed32, sfixed64,
       * uint32, uint64,fixed32, fixed64.
       * </pre>
       *
       * <code>optional string basic = 101;</code>
       * @return The bytes for basic.
       */
      public com.google.protobuf.ByteString
          getBasicBytes() {
        java.lang.Object ref = basic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          basic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Set default value for field that types includes:
       * string, enum, bool,
       * int32, int64, sint32, sint64, sfixed32, sfixed64,
       * uint32, uint64,fixed32, fixed64.
       * </pre>
       *
       * <code>optional string basic = 101;</code>
       * @param value The basic to set.
       * @return This builder for chaining.
       */
      public Builder setBasic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        basic_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Set default value for field that types includes:
       * string, enum, bool,
       * int32, int64, sint32, sint64, sfixed32, sfixed64,
       * uint32, uint64,fixed32, fixed64.
       * </pre>
       *
       * <code>optional string basic = 101;</code>
       * @return This builder for chaining.
       */
      public Builder clearBasic() {
        bitField0_ = (bitField0_ & ~0x00000001);
        basic_ = getDefaultInstance().getBasic();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Set default value for field that types includes:
       * string, enum, bool,
       * int32, int64, sint32, sint64, sfixed32, sfixed64,
       * uint32, uint64,fixed32, fixed64.
       * </pre>
       *
       * <code>optional string basic = 101;</code>
       * @param value The bytes for basic to set.
       * @return This builder for chaining.
       */
      public Builder setBasicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        basic_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList array_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureArrayIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          array_ = new com.google.protobuf.LazyStringArrayList(array_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       * Set default value for field of types repeated.
       * </pre>
       *
       * <code>repeated string array = 102;</code>
       * @return A list containing the array.
       */
      public com.google.protobuf.ProtocolStringList
          getArrayList() {
        return array_.getUnmodifiableView();
      }
      /**
       * <pre>
       * Set default value for field of types repeated.
       * </pre>
       *
       * <code>repeated string array = 102;</code>
       * @return The count of array.
       */
      public int getArrayCount() {
        return array_.size();
      }
      /**
       * <pre>
       * Set default value for field of types repeated.
       * </pre>
       *
       * <code>repeated string array = 102;</code>
       * @param index The index of the element to return.
       * @return The array at the given index.
       */
      public java.lang.String getArray(int index) {
        return array_.get(index);
      }
      /**
       * <pre>
       * Set default value for field of types repeated.
       * </pre>
       *
       * <code>repeated string array = 102;</code>
       * @param index The index of the value to return.
       * @return The bytes of the array at the given index.
       */
      public com.google.protobuf.ByteString
          getArrayBytes(int index) {
        return array_.getByteString(index);
      }
      /**
       * <pre>
       * Set default value for field of types repeated.
       * </pre>
       *
       * <code>repeated string array = 102;</code>
       * @param index The index to set the value at.
       * @param value The array to set.
       * @return This builder for chaining.
       */
      public Builder setArray(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArrayIsMutable();
        array_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Set default value for field of types repeated.
       * </pre>
       *
       * <code>repeated string array = 102;</code>
       * @param value The array to add.
       * @return This builder for chaining.
       */
      public Builder addArray(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArrayIsMutable();
        array_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Set default value for field of types repeated.
       * </pre>
       *
       * <code>repeated string array = 102;</code>
       * @param values The array to add.
       * @return This builder for chaining.
       */
      public Builder addAllArray(
          java.lang.Iterable<java.lang.String> values) {
        ensureArrayIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, array_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Set default value for field of types repeated.
       * </pre>
       *
       * <code>repeated string array = 102;</code>
       * @return This builder for chaining.
       */
      public Builder clearArray() {
        array_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Set default value for field of types repeated.
       * </pre>
       *
       * <code>repeated string array = 102;</code>
       * @param value The bytes of the array to add.
       * @return This builder for chaining.
       */
      public Builder addArrayBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureArrayIsMutable();
        array_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> map_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMap() {
        if (map_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MapDefaultEntryHolder.defaultEntry);
        }
        return map_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableMap() {
        onChanged();;
        if (map_ == null) {
          map_ = com.google.protobuf.MapField.newMapField(
              MapDefaultEntryHolder.defaultEntry);
        }
        if (!map_.isMutable()) {
          map_ = map_.copy();
        }
        return map_;
      }

      public int getMapCount() {
        return internalGetMap().getMap().size();
      }
      /**
       * <pre>
       * Set default value for field of types map.
       * </pre>
       *
       * <code>map&lt;string, string&gt; map = 103;</code>
       */

      @java.lang.Override
      public boolean containsMap(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMapMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getMap() {
        return getMapMap();
      }
      /**
       * <pre>
       * Set default value for field of types map.
       * </pre>
       *
       * <code>map&lt;string, string&gt; map = 103;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getMapMap() {
        return internalGetMap().getMap();
      }
      /**
       * <pre>
       * Set default value for field of types map.
       * </pre>
       *
       * <code>map&lt;string, string&gt; map = 103;</code>
       */
      @java.lang.Override

      public java.lang.String getMapOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * Set default value for field of types map.
       * </pre>
       *
       * <code>map&lt;string, string&gt; map = 103;</code>
       */
      @java.lang.Override

      public java.lang.String getMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMap() {
        internalGetMutableMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * Set default value for field of types map.
       * </pre>
       *
       * <code>map&lt;string, string&gt; map = 103;</code>
       */

      public Builder removeMap(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableMap() {
        return internalGetMutableMap().getMutableMap();
      }
      /**
       * <pre>
       * Set default value for field of types map.
       * </pre>
       *
       * <code>map&lt;string, string&gt; map = 103;</code>
       */
      public Builder putMap(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) {
  throw new NullPointerException("map value");
}

        internalGetMutableMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * Set default value for field of types map.
       * </pre>
       *
       * <code>map&lt;string, string&gt; map = 103;</code>
       */

      public Builder putAllMap(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableMap().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:defaults.FieldOptions)
    }

    // @@protoc_insertion_point(class_scope:defaults.FieldOptions)
    private static final com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions();
    }

    public static com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FieldOptions>
        PARSER = new com.google.protobuf.AbstractParser<FieldOptions>() {
      @java.lang.Override
      public FieldOptions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FieldOptions(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FieldOptions> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FieldOptions> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OneOfOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:defaults.OneOfOptions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The field name that in oneof part.
     * </pre>
     *
     * <code>optional string field = 1;</code>
     * @return Whether the field field is set.
     */
    boolean hasField();
    /**
     * <pre>
     * The field name that in oneof part.
     * </pre>
     *
     * <code>optional string field = 1;</code>
     * @return The field.
     */
    java.lang.String getField();
    /**
     * <pre>
     * The field name that in oneof part.
     * </pre>
     *
     * <code>optional string field = 1;</code>
     * @return The bytes for field.
     */
    com.google.protobuf.ByteString
        getFieldBytes();
  }
  /**
   * Protobuf type {@code defaults.OneOfOptions}
   */
  public static final class OneOfOptions extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:defaults.OneOfOptions)
      OneOfOptionsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OneOfOptions.newBuilder() to construct.
    private OneOfOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OneOfOptions() {
      field_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OneOfOptions();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OneOfOptions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              field_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.yu31.protoc.pbdefaults.PBDefaults.internal_static_defaults_OneOfOptions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.yu31.protoc.pbdefaults.PBDefaults.internal_static_defaults_OneOfOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions.class, com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions.Builder.class);
    }

    private int bitField0_;
    public static final int FIELD_FIELD_NUMBER = 1;
    private volatile java.lang.Object field_;
    /**
     * <pre>
     * The field name that in oneof part.
     * </pre>
     *
     * <code>optional string field = 1;</code>
     * @return Whether the field field is set.
     */
    @java.lang.Override
    public boolean hasField() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The field name that in oneof part.
     * </pre>
     *
     * <code>optional string field = 1;</code>
     * @return The field.
     */
    @java.lang.Override
    public java.lang.String getField() {
      java.lang.Object ref = field_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The field name that in oneof part.
     * </pre>
     *
     * <code>optional string field = 1;</code>
     * @return The bytes for field.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFieldBytes() {
      java.lang.Object ref = field_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, field_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, field_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions)) {
        return super.equals(obj);
      }
      com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions other = (com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions) obj;

      if (hasField() != other.hasField()) return false;
      if (hasField()) {
        if (!getField()
            .equals(other.getField())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasField()) {
        hash = (37 * hash) + FIELD_FIELD_NUMBER;
        hash = (53 * hash) + getField().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code defaults.OneOfOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:defaults.OneOfOptions)
        com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.yu31.protoc.pbdefaults.PBDefaults.internal_static_defaults_OneOfOptions_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.yu31.protoc.pbdefaults.PBDefaults.internal_static_defaults_OneOfOptions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions.class, com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions.Builder.class);
      }

      // Construct using com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        field_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.yu31.protoc.pbdefaults.PBDefaults.internal_static_defaults_OneOfOptions_descriptor;
      }

      @java.lang.Override
      public com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions getDefaultInstanceForType() {
        return com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions build() {
        com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions buildPartial() {
        com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions result = new com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.field_ = field_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions) {
          return mergeFrom((com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions other) {
        if (other == com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions.getDefaultInstance()) return this;
        if (other.hasField()) {
          bitField0_ |= 0x00000001;
          field_ = other.field_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object field_ = "";
      /**
       * <pre>
       * The field name that in oneof part.
       * </pre>
       *
       * <code>optional string field = 1;</code>
       * @return Whether the field field is set.
       */
      public boolean hasField() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * The field name that in oneof part.
       * </pre>
       *
       * <code>optional string field = 1;</code>
       * @return The field.
       */
      public java.lang.String getField() {
        java.lang.Object ref = field_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          field_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The field name that in oneof part.
       * </pre>
       *
       * <code>optional string field = 1;</code>
       * @return The bytes for field.
       */
      public com.google.protobuf.ByteString
          getFieldBytes() {
        java.lang.Object ref = field_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          field_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The field name that in oneof part.
       * </pre>
       *
       * <code>optional string field = 1;</code>
       * @param value The field to set.
       * @return This builder for chaining.
       */
      public Builder setField(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        field_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The field name that in oneof part.
       * </pre>
       *
       * <code>optional string field = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearField() {
        bitField0_ = (bitField0_ & ~0x00000001);
        field_ = getDefaultInstance().getField();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The field name that in oneof part.
       * </pre>
       *
       * <code>optional string field = 1;</code>
       * @param value The bytes for field to set.
       * @return This builder for chaining.
       */
      public Builder setFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        field_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:defaults.OneOfOptions)
    }

    // @@protoc_insertion_point(class_scope:defaults.OneOfOptions)
    private static final com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions();
    }

    public static com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OneOfOptions>
        PARSER = new com.google.protobuf.AbstractParser<OneOfOptions>() {
      @java.lang.Override
      public OneOfOptions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OneOfOptions(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OneOfOptions> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OneOfOptions> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int FIELD_FIELD_NUMBER = 64020;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions> field = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions.class,
        com.github.yu31.protoc.pbdefaults.PBDefaults.FieldOptions.getDefaultInstance());
  public static final int ONEOF_FIELD_NUMBER = 64021;
  /**
   * <code>extend .google.protobuf.OneofOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.OneofOptions,
      com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions> oneof = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions.class,
        com.github.yu31.protoc.pbdefaults.PBDefaults.OneOfOptions.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_defaults_FieldOptions_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_defaults_FieldOptions_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_defaults_FieldOptions_MapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_defaults_FieldOptions_MapEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_defaults_OneOfOptions_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_defaults_OneOfOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016defaults.proto\022\010defaults\032 google/proto" +
      "buf/descriptor.proto\"\225\001\n\014FieldOptions\022\022\n" +
      "\005basic\030e \001(\tH\000\210\001\001\022\r\n\005array\030f \003(\t\022,\n\003map\030" +
      "g \003(\0132\037.defaults.FieldOptions.MapEntry\032*" +
      "\n\010MapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\002" +
      "8\001B\010\n\006_basic\",\n\014OneOfOptions\022\022\n\005field\030\001 " +
      "\001(\tH\000\210\001\001B\010\n\006_field:F\n\005field\022\035.google.pro" +
      "tobuf.FieldOptions\030\224\364\003 \001(\0132\026.defaults.Fi" +
      "eldOptions:F\n\005oneof\022\035.google.protobuf.On" +
      "eofOptions\030\225\364\003 \001(\0132\026.defaults.OneOfOptio" +
      "nsBb\n!com.github.yu31.protoc.pbdefaultsB" +
      "\nPBDefaultsP\000Z/github.com/yu31/protoc-pl" +
      "ugin/xgo/pb/pbdefaultsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_defaults_FieldOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_defaults_FieldOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_defaults_FieldOptions_descriptor,
        new java.lang.String[] { "Basic", "Array", "Map", "Basic", });
    internal_static_defaults_FieldOptions_MapEntry_descriptor =
      internal_static_defaults_FieldOptions_descriptor.getNestedTypes().get(0);
    internal_static_defaults_FieldOptions_MapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_defaults_FieldOptions_MapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_defaults_OneOfOptions_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_defaults_OneOfOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_defaults_OneOfOptions_descriptor,
        new java.lang.String[] { "Field", "Field", });
    field.internalInit(descriptor.getExtensions().get(0));
    oneof.internalInit(descriptor.getExtensions().get(1));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
