// Code generated by protoc-gen-godefaults. DO NOT EDIT.
// versions:
// 		protoc-gen-godefaults 0.0.2
// source: xgo/tests/godefaultstest/godefaults_test_external2.proto

package godefaultstest

import (
	_ "github.com/yu31/protoc-plugin/xgo/pb/pbdefaults"
	godefaultsexternal "github.com/yu31/protoc-plugin/xgo/tests/godefaultsexternal"
)

// Set default value for message godefaultstest.MessageExternal2
func (this *MessageExternal2) SetDefaults() {
	if this == nil {
		return
	}
	switch v := this.OneType1.(type) {
	case *MessageExternal2_Status:
		if v.Status == 0 {
			v.Status = godefaultsexternal.ExternalMessage1_EmbedEnum1(1)
		}
	default:
		_ = v // to avoid unused panic
	}
	return
}
